import { describe, expect, it } from "vitest";
import { createTestDb } from "../test-db.js";
import { schemaSql } from "./schema.js";

describe("migrate", () => {
  it("creates core bot tables and seed state", async () => {
    const db = await createTestDb();

    const tables = (await db.all<{ name: string }>(
      "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name"
    )).map((row) => row.name);

    expect(tables).toContain("bot_state");
    expect(tables).toContain("experience_candidates");
    expect(tables).toContain("experience_logs");
    expect(tables).toContain("posts");
    expect(tables).toContain("m_emotion_asset");
    expect(tables).toContain("m_runtime_setting");
    expect(await db.get("SELECT COUNT(*) AS count FROM bot_state")).toEqual({ count: 1 });
  });

  it("seeds runtime settings in one table", async () => {
    const db = await createTestDb();

    await expect(
      db.get(
        "SELECT setting_value, value_type, category FROM m_runtime_setting WHERE setting_key = 'CHUTES_MODEL_TEXT'"
      )
    ).resolves.toEqual({
      setting_value: "moonshotai/Kimi-K2.5-TEE",
      value_type: "string",
      category: "ai"
    });
    await expect(
      db.get(
        "SELECT setting_value, value_type, category FROM m_runtime_setting WHERE setting_key = 'POST_PROBABILITY_30_MIN'"
      )
    ).resolves.toEqual({
      setting_value: "0.80",
      value_type: "number",
      category: "scheduling"
    });
  });

  it("uses postgres identity columns for autoincrement tables", () => {
    expect(schemaSql("postgres")).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(schemaSql("postgres")).not.toContain("AUTOINCREMENT");
  });

  it("is idempotent", async () => {
    const db = await createTestDb();
    await db.exec(schemaSql("sqlite"));
    expect(await db.get("SELECT COUNT(*) AS count FROM bot_state")).toEqual({ count: 1 });
  });
});
