import { describe, expect, it } from "vitest";
import { createTestDb } from "../test-db.js";
import { schemaSql } from "./schema.js";

describe("migrate", () => {
  it("creates core bot tables and seed state", async () => {
    const db = await createTestDb();

    const tables = (await db.all<{ name: string }>(
      "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name"
    )).map((row) => row.name);

    expect(tables).toContain("bot_state");
    expect(tables).toContain("experience_candidates");
    expect(tables).toContain("experience_logs");
    expect(tables).toContain("posts");
    expect(tables).toContain("m_emotion_asset");
    expect(await db.get("SELECT COUNT(*) AS count FROM bot_state")).toEqual({ count: 1 });
  });

  it("uses postgres identity columns for autoincrement tables", () => {
    expect(schemaSql("postgres")).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(schemaSql("postgres")).not.toContain("AUTOINCREMENT");
  });

  it("is idempotent", async () => {
    const db = await createTestDb();
    await db.exec(schemaSql("sqlite"));
    expect(await db.get("SELECT COUNT(*) AS count FROM bot_state")).toEqual({ count: 1 });
  });
});
